project:
  type: website
  output-dir: docs

website:
  title: "CyberSec Lab"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Cloud
        menu:
          - text: AWS IAM
            href: cloud/aws-iam.qmd
          - text: Audit & Monitoring
            href: cloud/logging.qmd
      - text: Compliance
        menu:
          - text: NIST AI
            href: compliance/nistai.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Resources
        href: resources/index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: darkly
    toc: true
