project:
  type: website
  output-dir: docs

website:
  title: "CyberSec Lab"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Blue Team
        menu:
          - text: SIEM & Logging
            href: blueteam/siem.qmd
          - text: Incident Response
            href: blueteam/ir.qmd
          - text: Hardening & Monitoring
            href: blueteam/hardening.qmd
      - text: Red Team
        menu:
          - text: Web App Hacking
            href: redteam/web.qmd
          - text: Recon & OSINT
            href: redteam/recon.qmd
          - text: Exploitation Labs
            href: redteam/exploits.qmd
      - text: Cloud
        menu:
          - text: AWS IAM
            href: cloud/aws-iam.qmd
          - text: Audit & Monitoring
            href: cloud/logging.qmd
      - text: Compliance
        menu:
          - text: NIST 800-53
            href: compliance/nist.qmd
          - text: STIG Checklists
            href: compliance/stig.qmd
          - text: CIS Benchmarks
            href: compliance/cis.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Resources
        href: resources/index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: darkly
    toc: true
